### ISSUE TITLE
tile resolution

### ISSUE THREAD

**Issue by brry** [paleolimbot/rosm#30]
In #13, you suggest zooming in for higher resolution. Apparently, [OpenStreetMap](https://github.com/ifellows/ROSM) (to be taken off CRAN next week) has a different tile fetching mechanism, because at a particular zoom level, the images have better resolution. 

Is it worth looking into how Ian's code does this? It does look a lot nicer in larger images.

For my package [OSMscale](https://github.com/brry/OSMscale/issues/1#issuecomment-1752906486), I have also looked into `maptiles`, but despite [not projecting](https://github.com/riatelab/maptiles/issues/5), it has the same fuzzyness as `rosm`.

Here is the comparison:

![maps1](https://github.com/paleolimbot/rosm/assets/8860095/395937a6-42ac-4c81-bc88-8c017d79f503)
![maps2](https://github.com/paleolimbot/rosm/assets/8860095/1ad3e679-b609-42a8-bb11-f4beb14767e2)

And here's the code generating it (bbox management can probably be improved, but that's not the point here ^^)

```r
d <- read.table(sep=",", header=TRUE, text=
"lat, long
52.514464, 13.350137
52.370000, 13.120000
55.685143, 12.580008
50.106452, 14.419989
48.847003, 2.3372130
51.505364,-0.1647520")

png("maps%d.png", width=2, height=2, units="in", res=200)

# OpenStreetMap ----
OSMscale::pointsMap(lat, long, data=d, fx=0, scale=FALSE, pch=NA, zoom=5)
title(main="OpenStreetMap", line=-1)

# rosm ----
dsf <- sf::st_as_sf(d, coords=c("long", "lat"), crs=4326)
bounds2 <- sf::st_bbox(sf::st_transform(dsf, "EPSG:3857"))
bounds2 <- wk::rct(bounds2$xmin, bounds2$ymin, bounds2$xmax, bounds2$ymax, crs="EPSG:3857")
rmap <- rosm::osm_raster(bounds2, rosm::osm_url_spec())
rmap <- wk::grd_crop(rmap, bounds2)
plot(rmap, yaxt="n")
title(main="rosm", line=-1)

dev.off()
```

**Comment by mdsumner** [comment]
try the zoom arg, increase its value by 1

I tried running the code to investigate but baulked at rJava, sorry 🙏

there are other ways to read directly via gdal if you're interested, the warp util in stars is probably the easiest but needs a bit of setup (target extent, dimension, crs,and the src dsn of the tile server which, see the WMS gdal driver, or I can help) 🙏

**Comment by mdsumner** [comment]
fwiw I tried this without OSMScale setup, I guessed at zoom 6 (seems like 5 is chosen natively in this case)

```R
rmap <- rosm::osm_raster(bounds2, rosm::osm_url_spec(), zoom = 6)

rmap <- wk::grd_crop(rmap, bounds2)
plot(rmap, yaxt="n")
title(main="rosm", line=-1)
```

![image](https://github.com/paleolimbot/rosm/assets/4107631/c61b845c-d575-400f-a62f-7ea04ca0e3e6)

it looks quite a lot better to me, I expect rosm has a way to report the zoom chosen (it's not so hard to calculate but I don't have it on hand)

there's not anything systematic in R for matching raster sources to devices sadly, but the pieces are all there in various ways, as a safe heuristic set `zoom = 1` and see how big it is, then go up until happy :)

**Comment by brry** [comment]
Thanks for looking into this!  
The original zoom is 5 in both cases (intentionally so, to not have too many details on the map).

I guess most people will be fine with a higher zoom level (and then the resolution is fine).  
Also, OpenStreetMap is being updated for CRAN, which means I can continue to use that for my case.  
i.e. on my behalf there's no need to follow up on this issue and you may close it.

PS: if xou do want to look at the variant with Java, consider my [installation tips](https://bookdown.org/brry/course/packages.html#rjava-on-windows).

**Comment by brry** [comment]
The issue is solved in `terra::plotRGB`, see https://github.com/riatelab/maptiles/issues/27#issuecomment-1761064307 :)
